---
title: "Welcome!"
---
**Workshop Organizers:** Kelsey Andersen Onofre, Rodrigo Onofre, Karen Garrett, Felipe Dalla Lana, Adam Sparks, Mladen Cucak


### Data Visualization in R


Introductory paragraph

### Workshop Logistics   
\  

#### WORKSHOP: Data Visualization in R
#### Tuesday, Feb 9th 1:00pm-4:00pm  CST

\  

### Pre-Workshop Set Up

Make sure you have the most recent versions of R and R Studio Installed on your computer.  

To download R:  
1. Go to https://cran.r-project.org/  
2. Click "Download R for Mac/Windows"  
3. Download the appropriate file:  
   - Windows users click Base, and download the installer for the latest R version  
   - Mac users select the file R-3.X.X that aligns with your OS version  
4. Follow the instructions of the installer   

To download RStudio:  
1. Go to RStudio for desktop https://www.rstudio.com/products/rstudio/download/#download  
2. Select the install file for your OS  
3. Follow the instructions of the installer  

Also, it would be useful to download the following R packages prior to the workshop:  

*	ggplot2
*	ggpuber
*	patchwork
*	ggraph
*	sf
*	ggmap
*	packages for choosing color themes
*	tidyverse
*	...


For new R useRs: open R studio and type the following code into the console, OR you can go over the "Packages" tab in the bottom right hand corner of R studio, click "install", and type in the names of the packages that you would like to install. Once you have installed a package on your computer, there is no need to install again. Instead, each time you need to use the package you use the *library()* code (as shown below). 
```
install.packages("igraph")

library(igraph) 

install.packages("Hmisc")

library(Hmisc) 

install.packages("Matrix")

library(Matrix)  
```
It is higly recomended to go through materials for the Intro to R for Plant Pathologists course:
https://everhartlab.github.io/APS_IntroR_2020/  
and video can be found on: 
https://www.apsnet.org/edcenter/resources/Webinars/ondemand/Pages/Part_1_IntroToR.aspx 

## insert logo from institutions sponsoring this workship (K-State, Penn State, K-State)